# Generated by Django 3.1 on 2020-12-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_is_certified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_certified',
            new_name='is_verified',
        ),
    ]
